# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KitaTesterProto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15KitaTesterProto.proto\"+\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x12\n\nparameters\x18\x02 \x03(\t\"\x91\x02\n\x0cQuoteMessage\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0b\n\x03\x62id\x18\x02 \x01(\x01\x12\x0b\n\x03\x61sk\x18\x03 \x01(\x01\x12\x13\n\x0bminute1Open\x18\x04 \x01(\x01\x12\x11\n\thour1Open\x18\x05 \x01(\x01\x12\x11\n\thour2Open\x18\x06 \x01(\x01\x12\x10\n\x08\x64\x61y1Open\x18\x07 \x01(\x01\x12\x11\n\thour1High\x18\x08 \x01(\x01\x12\x10\n\x08hour1Low\x18\t \x01(\x01\x12\x12\n\nhour1Close\x18\n \x01(\x01\x12\x11\n\thour2High\x18\x0b \x01(\x01\x12\x10\n\x08hour2Low\x18\x0c \x01(\x01\x12\x12\n\nhour2Close\x18\r \x01(\x01\x12\x15\n\rday1Timestamp\x18\x0e \x01(\x01\"B\n\x15PythonResponseMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05para1\x18\x02 \x01(\t\x12\x0e\n\x06is_end\x18\x03 \x01(\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'KitaTesterProto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TASK._serialized_start=25
  _TASK._serialized_end=68
  _QUOTEMESSAGE._serialized_start=71
  _QUOTEMESSAGE._serialized_end=344
  _PYTHONRESPONSEMESSAGE._serialized_start=346
  _PYTHONRESPONSEMESSAGE._serialized_end=412
# @@protoc_insertion_point(module_scope)
