def initialize(login: int, server: str, password: str) -> bool: ...
def shutdown() -> None: ...
def last_error() -> str: ...
def symbols_get(group: str) -> list[str]: ...
def symbol_select(symbol: str, enable: bool) -> bool: ...


# def order_send(order: Any) -> dict: ...

# end of file
