// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: KitaTesterProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from KitaTesterProto.proto</summary>
public static partial class KitaTesterProtoReflection {

  #region Descriptor
  /// <summary>File descriptor for KitaTesterProto.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static KitaTesterProtoReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChVLaXRhVGVzdGVyUHJvdG8ucHJvdG8iKwoEVGFzaxIPCgd0YXNrX2lkGAEg",
          "ASgFEhIKCnBhcmFtZXRlcnMYAiADKAkizgIKDFF1b3RlTWVzc2FnZRIRCgl0",
          "aW1lc3RhbXAYASABKAESCwoDYmlkGAIgASgBEgsKA2FzaxgDIAEoARITCgtt",
          "aW51dGUxT3BlbhgEIAEoARIRCglob3VyMU9wZW4YBSABKAESEQoJaG91cjJP",
          "cGVuGAYgASgBEhAKCGRheTFPcGVuGAcgASgBEhEKCWhvdXIxSGlnaBgIIAEo",
          "ARIQCghob3VyMUxvdxgJIAEoARISCgpob3VyMUNsb3NlGAogASgBEhEKCWhv",
          "dXIySGlnaBgLIAEoARIQCghob3VyMkxvdxgMIAEoARISCgpob3VyMkNsb3Nl",
          "GA0gASgBEhUKDWRheTFUaW1lc3RhbXAYDiABKAESDAoEc21hMRgPIAEoARIP",
          "CgdiYjFtYWluGBAgASgBEg0KBWJiMWhpGBEgASgBEg0KBWJiMWxvGBIgASgB",
          "IkIKFVB5dGhvblJlc3BvbnNlTWVzc2FnZRIKCgJpZBgBIAEoBRINCgVwYXJh",
          "MRgCIAEoCRIOCgZpc19lbmQYAyABKAhiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Task), global::Task.Parser, new[]{ "TaskId", "Parameters" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::QuoteMessage), global::QuoteMessage.Parser, new[]{ "Timestamp", "Bid", "Ask", "Minute1Open", "Hour1Open", "Hour2Open", "Day1Open", "Hour1High", "Hour1Low", "Hour1Close", "Hour2High", "Hour2Low", "Hour2Close", "Day1Timestamp", "Sma1", "Bb1Main", "Bb1Hi", "Bb1Lo" }, null, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::PythonResponseMessage), global::PythonResponseMessage.Parser, new[]{ "Id", "Para1", "IsEnd" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Task : pb::IMessage<Task>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<Task> _parser = new pb::MessageParser<Task>(() => new Task());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<Task> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::KitaTesterProtoReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Task() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Task(Task other) : this() {
    taskId_ = other.taskId_;
    parameters_ = other.parameters_.Clone();
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public Task Clone() {
    return new Task(this);
  }

  /// <summary>Field number for the "task_id" field.</summary>
  public const int TaskIdFieldNumber = 1;
  private int taskId_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int TaskId {
    get { return taskId_; }
    set {
      taskId_ = value;
    }
  }

  /// <summary>Field number for the "parameters" field.</summary>
  public const int ParametersFieldNumber = 2;
  private static readonly pb::FieldCodec<string> _repeated_parameters_codec
      = pb::FieldCodec.ForString(18);
  private readonly pbc::RepeatedField<string> parameters_ = new pbc::RepeatedField<string>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<string> Parameters {
    get { return parameters_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as Task);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(Task other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (TaskId != other.TaskId) return false;
    if(!parameters_.Equals(other.parameters_)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (TaskId != 0) hash ^= TaskId.GetHashCode();
    hash ^= parameters_.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (TaskId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(TaskId);
    }
    parameters_.WriteTo(output, _repeated_parameters_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (TaskId != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(TaskId);
    }
    parameters_.WriteTo(ref output, _repeated_parameters_codec);
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (TaskId != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(TaskId);
    }
    size += parameters_.CalculateSize(_repeated_parameters_codec);
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(Task other) {
    if (other == null) {
      return;
    }
    if (other.TaskId != 0) {
      TaskId = other.TaskId;
    }
    parameters_.Add(other.parameters_);
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          TaskId = input.ReadInt32();
          break;
        }
        case 18: {
          parameters_.AddEntriesFrom(input, _repeated_parameters_codec);
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          TaskId = input.ReadInt32();
          break;
        }
        case 18: {
          parameters_.AddEntriesFrom(ref input, _repeated_parameters_codec);
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class QuoteMessage : pb::IMessage<QuoteMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<QuoteMessage> _parser = new pb::MessageParser<QuoteMessage>(() => new QuoteMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<QuoteMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::KitaTesterProtoReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public QuoteMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public QuoteMessage(QuoteMessage other) : this() {
    timestamp_ = other.timestamp_;
    bid_ = other.bid_;
    ask_ = other.ask_;
    minute1Open_ = other.minute1Open_;
    hour1Open_ = other.hour1Open_;
    hour2Open_ = other.hour2Open_;
    day1Open_ = other.day1Open_;
    hour1High_ = other.hour1High_;
    hour1Low_ = other.hour1Low_;
    hour1Close_ = other.hour1Close_;
    hour2High_ = other.hour2High_;
    hour2Low_ = other.hour2Low_;
    hour2Close_ = other.hour2Close_;
    day1Timestamp_ = other.day1Timestamp_;
    sma1_ = other.sma1_;
    bb1Main_ = other.bb1Main_;
    bb1Hi_ = other.bb1Hi_;
    bb1Lo_ = other.bb1Lo_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public QuoteMessage Clone() {
    return new QuoteMessage(this);
  }

  /// <summary>Field number for the "timestamp" field.</summary>
  public const int TimestampFieldNumber = 1;
  private double timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Timestamp {
    get { return timestamp_; }
    set {
      timestamp_ = value;
    }
  }

  /// <summary>Field number for the "bid" field.</summary>
  public const int BidFieldNumber = 2;
  private double bid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Bid {
    get { return bid_; }
    set {
      bid_ = value;
    }
  }

  /// <summary>Field number for the "ask" field.</summary>
  public const int AskFieldNumber = 3;
  private double ask_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Ask {
    get { return ask_; }
    set {
      ask_ = value;
    }
  }

  /// <summary>Field number for the "minute1Open" field.</summary>
  public const int Minute1OpenFieldNumber = 4;
  private double minute1Open_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Minute1Open {
    get { return minute1Open_; }
    set {
      minute1Open_ = value;
    }
  }

  /// <summary>Field number for the "hour1Open" field.</summary>
  public const int Hour1OpenFieldNumber = 5;
  private double hour1Open_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Hour1Open {
    get { return hour1Open_; }
    set {
      hour1Open_ = value;
    }
  }

  /// <summary>Field number for the "hour2Open" field.</summary>
  public const int Hour2OpenFieldNumber = 6;
  private double hour2Open_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Hour2Open {
    get { return hour2Open_; }
    set {
      hour2Open_ = value;
    }
  }

  /// <summary>Field number for the "day1Open" field.</summary>
  public const int Day1OpenFieldNumber = 7;
  private double day1Open_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Day1Open {
    get { return day1Open_; }
    set {
      day1Open_ = value;
    }
  }

  /// <summary>Field number for the "hour1High" field.</summary>
  public const int Hour1HighFieldNumber = 8;
  private double hour1High_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Hour1High {
    get { return hour1High_; }
    set {
      hour1High_ = value;
    }
  }

  /// <summary>Field number for the "hour1Low" field.</summary>
  public const int Hour1LowFieldNumber = 9;
  private double hour1Low_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Hour1Low {
    get { return hour1Low_; }
    set {
      hour1Low_ = value;
    }
  }

  /// <summary>Field number for the "hour1Close" field.</summary>
  public const int Hour1CloseFieldNumber = 10;
  private double hour1Close_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Hour1Close {
    get { return hour1Close_; }
    set {
      hour1Close_ = value;
    }
  }

  /// <summary>Field number for the "hour2High" field.</summary>
  public const int Hour2HighFieldNumber = 11;
  private double hour2High_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Hour2High {
    get { return hour2High_; }
    set {
      hour2High_ = value;
    }
  }

  /// <summary>Field number for the "hour2Low" field.</summary>
  public const int Hour2LowFieldNumber = 12;
  private double hour2Low_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Hour2Low {
    get { return hour2Low_; }
    set {
      hour2Low_ = value;
    }
  }

  /// <summary>Field number for the "hour2Close" field.</summary>
  public const int Hour2CloseFieldNumber = 13;
  private double hour2Close_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Hour2Close {
    get { return hour2Close_; }
    set {
      hour2Close_ = value;
    }
  }

  /// <summary>Field number for the "day1Timestamp" field.</summary>
  public const int Day1TimestampFieldNumber = 14;
  private double day1Timestamp_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Day1Timestamp {
    get { return day1Timestamp_; }
    set {
      day1Timestamp_ = value;
    }
  }

  /// <summary>Field number for the "sma1" field.</summary>
  public const int Sma1FieldNumber = 15;
  private double sma1_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Sma1 {
    get { return sma1_; }
    set {
      sma1_ = value;
    }
  }

  /// <summary>Field number for the "bb1main" field.</summary>
  public const int Bb1MainFieldNumber = 16;
  private double bb1Main_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Bb1Main {
    get { return bb1Main_; }
    set {
      bb1Main_ = value;
    }
  }

  /// <summary>Field number for the "bb1hi" field.</summary>
  public const int Bb1HiFieldNumber = 17;
  private double bb1Hi_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Bb1Hi {
    get { return bb1Hi_; }
    set {
      bb1Hi_ = value;
    }
  }

  /// <summary>Field number for the "bb1lo" field.</summary>
  public const int Bb1LoFieldNumber = 18;
  private double bb1Lo_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public double Bb1Lo {
    get { return bb1Lo_; }
    set {
      bb1Lo_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as QuoteMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(QuoteMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Timestamp, other.Timestamp)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Bid, other.Bid)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Ask, other.Ask)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Minute1Open, other.Minute1Open)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Hour1Open, other.Hour1Open)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Hour2Open, other.Hour2Open)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Day1Open, other.Day1Open)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Hour1High, other.Hour1High)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Hour1Low, other.Hour1Low)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Hour1Close, other.Hour1Close)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Hour2High, other.Hour2High)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Hour2Low, other.Hour2Low)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Hour2Close, other.Hour2Close)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Day1Timestamp, other.Day1Timestamp)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Sma1, other.Sma1)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Bb1Main, other.Bb1Main)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Bb1Hi, other.Bb1Hi)) return false;
    if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Bb1Lo, other.Bb1Lo)) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Timestamp != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Timestamp);
    if (Bid != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Bid);
    if (Ask != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Ask);
    if (Minute1Open != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Minute1Open);
    if (Hour1Open != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Hour1Open);
    if (Hour2Open != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Hour2Open);
    if (Day1Open != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Day1Open);
    if (Hour1High != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Hour1High);
    if (Hour1Low != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Hour1Low);
    if (Hour1Close != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Hour1Close);
    if (Hour2High != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Hour2High);
    if (Hour2Low != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Hour2Low);
    if (Hour2Close != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Hour2Close);
    if (Day1Timestamp != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Day1Timestamp);
    if (Sma1 != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Sma1);
    if (Bb1Main != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Bb1Main);
    if (Bb1Hi != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Bb1Hi);
    if (Bb1Lo != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Bb1Lo);
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Timestamp != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Timestamp);
    }
    if (Bid != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Bid);
    }
    if (Ask != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Ask);
    }
    if (Minute1Open != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Minute1Open);
    }
    if (Hour1Open != 0D) {
      output.WriteRawTag(41);
      output.WriteDouble(Hour1Open);
    }
    if (Hour2Open != 0D) {
      output.WriteRawTag(49);
      output.WriteDouble(Hour2Open);
    }
    if (Day1Open != 0D) {
      output.WriteRawTag(57);
      output.WriteDouble(Day1Open);
    }
    if (Hour1High != 0D) {
      output.WriteRawTag(65);
      output.WriteDouble(Hour1High);
    }
    if (Hour1Low != 0D) {
      output.WriteRawTag(73);
      output.WriteDouble(Hour1Low);
    }
    if (Hour1Close != 0D) {
      output.WriteRawTag(81);
      output.WriteDouble(Hour1Close);
    }
    if (Hour2High != 0D) {
      output.WriteRawTag(89);
      output.WriteDouble(Hour2High);
    }
    if (Hour2Low != 0D) {
      output.WriteRawTag(97);
      output.WriteDouble(Hour2Low);
    }
    if (Hour2Close != 0D) {
      output.WriteRawTag(105);
      output.WriteDouble(Hour2Close);
    }
    if (Day1Timestamp != 0D) {
      output.WriteRawTag(113);
      output.WriteDouble(Day1Timestamp);
    }
    if (Sma1 != 0D) {
      output.WriteRawTag(121);
      output.WriteDouble(Sma1);
    }
    if (Bb1Main != 0D) {
      output.WriteRawTag(129, 1);
      output.WriteDouble(Bb1Main);
    }
    if (Bb1Hi != 0D) {
      output.WriteRawTag(137, 1);
      output.WriteDouble(Bb1Hi);
    }
    if (Bb1Lo != 0D) {
      output.WriteRawTag(145, 1);
      output.WriteDouble(Bb1Lo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Timestamp != 0D) {
      output.WriteRawTag(9);
      output.WriteDouble(Timestamp);
    }
    if (Bid != 0D) {
      output.WriteRawTag(17);
      output.WriteDouble(Bid);
    }
    if (Ask != 0D) {
      output.WriteRawTag(25);
      output.WriteDouble(Ask);
    }
    if (Minute1Open != 0D) {
      output.WriteRawTag(33);
      output.WriteDouble(Minute1Open);
    }
    if (Hour1Open != 0D) {
      output.WriteRawTag(41);
      output.WriteDouble(Hour1Open);
    }
    if (Hour2Open != 0D) {
      output.WriteRawTag(49);
      output.WriteDouble(Hour2Open);
    }
    if (Day1Open != 0D) {
      output.WriteRawTag(57);
      output.WriteDouble(Day1Open);
    }
    if (Hour1High != 0D) {
      output.WriteRawTag(65);
      output.WriteDouble(Hour1High);
    }
    if (Hour1Low != 0D) {
      output.WriteRawTag(73);
      output.WriteDouble(Hour1Low);
    }
    if (Hour1Close != 0D) {
      output.WriteRawTag(81);
      output.WriteDouble(Hour1Close);
    }
    if (Hour2High != 0D) {
      output.WriteRawTag(89);
      output.WriteDouble(Hour2High);
    }
    if (Hour2Low != 0D) {
      output.WriteRawTag(97);
      output.WriteDouble(Hour2Low);
    }
    if (Hour2Close != 0D) {
      output.WriteRawTag(105);
      output.WriteDouble(Hour2Close);
    }
    if (Day1Timestamp != 0D) {
      output.WriteRawTag(113);
      output.WriteDouble(Day1Timestamp);
    }
    if (Sma1 != 0D) {
      output.WriteRawTag(121);
      output.WriteDouble(Sma1);
    }
    if (Bb1Main != 0D) {
      output.WriteRawTag(129, 1);
      output.WriteDouble(Bb1Main);
    }
    if (Bb1Hi != 0D) {
      output.WriteRawTag(137, 1);
      output.WriteDouble(Bb1Hi);
    }
    if (Bb1Lo != 0D) {
      output.WriteRawTag(145, 1);
      output.WriteDouble(Bb1Lo);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Timestamp != 0D) {
      size += 1 + 8;
    }
    if (Bid != 0D) {
      size += 1 + 8;
    }
    if (Ask != 0D) {
      size += 1 + 8;
    }
    if (Minute1Open != 0D) {
      size += 1 + 8;
    }
    if (Hour1Open != 0D) {
      size += 1 + 8;
    }
    if (Hour2Open != 0D) {
      size += 1 + 8;
    }
    if (Day1Open != 0D) {
      size += 1 + 8;
    }
    if (Hour1High != 0D) {
      size += 1 + 8;
    }
    if (Hour1Low != 0D) {
      size += 1 + 8;
    }
    if (Hour1Close != 0D) {
      size += 1 + 8;
    }
    if (Hour2High != 0D) {
      size += 1 + 8;
    }
    if (Hour2Low != 0D) {
      size += 1 + 8;
    }
    if (Hour2Close != 0D) {
      size += 1 + 8;
    }
    if (Day1Timestamp != 0D) {
      size += 1 + 8;
    }
    if (Sma1 != 0D) {
      size += 1 + 8;
    }
    if (Bb1Main != 0D) {
      size += 2 + 8;
    }
    if (Bb1Hi != 0D) {
      size += 2 + 8;
    }
    if (Bb1Lo != 0D) {
      size += 2 + 8;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(QuoteMessage other) {
    if (other == null) {
      return;
    }
    if (other.Timestamp != 0D) {
      Timestamp = other.Timestamp;
    }
    if (other.Bid != 0D) {
      Bid = other.Bid;
    }
    if (other.Ask != 0D) {
      Ask = other.Ask;
    }
    if (other.Minute1Open != 0D) {
      Minute1Open = other.Minute1Open;
    }
    if (other.Hour1Open != 0D) {
      Hour1Open = other.Hour1Open;
    }
    if (other.Hour2Open != 0D) {
      Hour2Open = other.Hour2Open;
    }
    if (other.Day1Open != 0D) {
      Day1Open = other.Day1Open;
    }
    if (other.Hour1High != 0D) {
      Hour1High = other.Hour1High;
    }
    if (other.Hour1Low != 0D) {
      Hour1Low = other.Hour1Low;
    }
    if (other.Hour1Close != 0D) {
      Hour1Close = other.Hour1Close;
    }
    if (other.Hour2High != 0D) {
      Hour2High = other.Hour2High;
    }
    if (other.Hour2Low != 0D) {
      Hour2Low = other.Hour2Low;
    }
    if (other.Hour2Close != 0D) {
      Hour2Close = other.Hour2Close;
    }
    if (other.Day1Timestamp != 0D) {
      Day1Timestamp = other.Day1Timestamp;
    }
    if (other.Sma1 != 0D) {
      Sma1 = other.Sma1;
    }
    if (other.Bb1Main != 0D) {
      Bb1Main = other.Bb1Main;
    }
    if (other.Bb1Hi != 0D) {
      Bb1Hi = other.Bb1Hi;
    }
    if (other.Bb1Lo != 0D) {
      Bb1Lo = other.Bb1Lo;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 9: {
          Timestamp = input.ReadDouble();
          break;
        }
        case 17: {
          Bid = input.ReadDouble();
          break;
        }
        case 25: {
          Ask = input.ReadDouble();
          break;
        }
        case 33: {
          Minute1Open = input.ReadDouble();
          break;
        }
        case 41: {
          Hour1Open = input.ReadDouble();
          break;
        }
        case 49: {
          Hour2Open = input.ReadDouble();
          break;
        }
        case 57: {
          Day1Open = input.ReadDouble();
          break;
        }
        case 65: {
          Hour1High = input.ReadDouble();
          break;
        }
        case 73: {
          Hour1Low = input.ReadDouble();
          break;
        }
        case 81: {
          Hour1Close = input.ReadDouble();
          break;
        }
        case 89: {
          Hour2High = input.ReadDouble();
          break;
        }
        case 97: {
          Hour2Low = input.ReadDouble();
          break;
        }
        case 105: {
          Hour2Close = input.ReadDouble();
          break;
        }
        case 113: {
          Day1Timestamp = input.ReadDouble();
          break;
        }
        case 121: {
          Sma1 = input.ReadDouble();
          break;
        }
        case 129: {
          Bb1Main = input.ReadDouble();
          break;
        }
        case 137: {
          Bb1Hi = input.ReadDouble();
          break;
        }
        case 145: {
          Bb1Lo = input.ReadDouble();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 9: {
          Timestamp = input.ReadDouble();
          break;
        }
        case 17: {
          Bid = input.ReadDouble();
          break;
        }
        case 25: {
          Ask = input.ReadDouble();
          break;
        }
        case 33: {
          Minute1Open = input.ReadDouble();
          break;
        }
        case 41: {
          Hour1Open = input.ReadDouble();
          break;
        }
        case 49: {
          Hour2Open = input.ReadDouble();
          break;
        }
        case 57: {
          Day1Open = input.ReadDouble();
          break;
        }
        case 65: {
          Hour1High = input.ReadDouble();
          break;
        }
        case 73: {
          Hour1Low = input.ReadDouble();
          break;
        }
        case 81: {
          Hour1Close = input.ReadDouble();
          break;
        }
        case 89: {
          Hour2High = input.ReadDouble();
          break;
        }
        case 97: {
          Hour2Low = input.ReadDouble();
          break;
        }
        case 105: {
          Hour2Close = input.ReadDouble();
          break;
        }
        case 113: {
          Day1Timestamp = input.ReadDouble();
          break;
        }
        case 121: {
          Sma1 = input.ReadDouble();
          break;
        }
        case 129: {
          Bb1Main = input.ReadDouble();
          break;
        }
        case 137: {
          Bb1Hi = input.ReadDouble();
          break;
        }
        case 145: {
          Bb1Lo = input.ReadDouble();
          break;
        }
      }
    }
  }
  #endif

}

public sealed partial class PythonResponseMessage : pb::IMessage<PythonResponseMessage>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<PythonResponseMessage> _parser = new pb::MessageParser<PythonResponseMessage>(() => new PythonResponseMessage());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<PythonResponseMessage> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::KitaTesterProtoReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PythonResponseMessage() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PythonResponseMessage(PythonResponseMessage other) : this() {
    id_ = other.id_;
    para1_ = other.para1_;
    isEnd_ = other.isEnd_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public PythonResponseMessage Clone() {
    return new PythonResponseMessage(this);
  }

  /// <summary>Field number for the "id" field.</summary>
  public const int IdFieldNumber = 1;
  private int id_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Id {
    get { return id_; }
    set {
      id_ = value;
    }
  }

  /// <summary>Field number for the "para1" field.</summary>
  public const int Para1FieldNumber = 2;
  private string para1_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Para1 {
    get { return para1_; }
    set {
      para1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "is_end" field.</summary>
  public const int IsEndFieldNumber = 3;
  private bool isEnd_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool IsEnd {
    get { return isEnd_; }
    set {
      isEnd_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as PythonResponseMessage);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(PythonResponseMessage other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Id != other.Id) return false;
    if (Para1 != other.Para1) return false;
    if (IsEnd != other.IsEnd) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (Id != 0) hash ^= Id.GetHashCode();
    if (Para1.Length != 0) hash ^= Para1.GetHashCode();
    if (IsEnd != false) hash ^= IsEnd.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Para1.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Para1);
    }
    if (IsEnd != false) {
      output.WriteRawTag(24);
      output.WriteBool(IsEnd);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (Id != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(Id);
    }
    if (Para1.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(Para1);
    }
    if (IsEnd != false) {
      output.WriteRawTag(24);
      output.WriteBool(IsEnd);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (Id != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
    }
    if (Para1.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Para1);
    }
    if (IsEnd != false) {
      size += 1 + 1;
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(PythonResponseMessage other) {
    if (other == null) {
      return;
    }
    if (other.Id != 0) {
      Id = other.Id;
    }
    if (other.Para1.Length != 0) {
      Para1 = other.Para1;
    }
    if (other.IsEnd != false) {
      IsEnd = other.IsEnd;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Para1 = input.ReadString();
          break;
        }
        case 24: {
          IsEnd = input.ReadBool();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Id = input.ReadInt32();
          break;
        }
        case 18: {
          Para1 = input.ReadString();
          break;
        }
        case 24: {
          IsEnd = input.ReadBool();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
